entidadbancaria/urls.py
from django.contrib import admin
from django.urls import path
from banco.views import accounts_list, transaction_create, account_update, accounts_create, account_delete, clients_list, clients_create, clients_update, clients_delete, TransactionsView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', clients_list, name='clients_list'),
    path('clients/create/', clients_create, name='client_new'),
    path('clients/edit/<int:pk>/', clients_update, name='client_edit'),
    path('clients/delete/<int:pk>/', clients_delete, name='client_delete'),
    path('accounts/<int:client>/', accounts_list, name='account_list'),
    path('accounts/create/<int:client_id>/', accounts_create, name='account_create'),
    path('accounts/update/<str:pk>/', account_update, name= 'account_update'),
    path('account/delete/<str:pk>', account_delete, name='account_delete'),
    path('transactions/<str:transaction>/', TransactionsView.as_view(), name='transactions_list'),
    path('transactoins/create/<str:account>/', transaction_create, name='transaction_create')
]

banco/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Cliente(models.Model):
  nombre = models.CharField(max_length=20)
  apellido_paterno = models.CharField(max_length= 20)
  apellido_materno = models.CharField(max_length= 20)
  fecha_registro = models.DateField()
  email = models.CharField(max_length=30)

  def __str__(self):
        return f'{self.nombre} ({self.apellido_paterno})'
  
  def get_absolute_url(self):
        return reverse('detalle-cliente', args=[str(self.pk)])
  
class Asesor(models.Model):  
  nombre = models.CharField(max_length=20)
  apellido_paterno = models.CharField(max_length= 20)
  apellido_materno = models.CharField(max_length= 20)

  def __str__(self):
      return f'{self.nombre} ({self.apellido_paterno})'
  
  def get_absolute_url(self):
        return reverse('detalle-asesor', args=[str(self.pk)])
  
import uuid

class Cuenta(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    cliente = models.ForeignKey(Cliente , on_delete = models.CASCADE)
    asesor = models.ManyToManyField(Asesor)
    feha_creacion = models.DateField()

    ACCOUNT_STATUS = (
      ('a', 'Activa'),
      ('i', 'Inactiva'),
      ('b', 'Baja'),
      ('c', 'Cerrada'),
    )

    status = models.CharField(
        max_length=1,
        choices=ACCOUNT_STATUS,
        default='a',
    )

    TYPE_ACCOUNT = (
      ('c', 'Corriente'),
      ('n', 'Nómina'),
      ('a', 'Ahorro'),
    )

    tipo_cuenta = models.CharField(
        max_length=1,
        choices=TYPE_ACCOUNT,
        default='c',
    )

    balance = models.DecimalField(decimal_places = 2, max_digits = 10)

    def __str__(self):
      return f'cuenta {self.id}'
  
    def get_absolute_url(self):
        return reverse('detalle-cuenta', args=[str(self.pk)])
        
class Transacciones(models.Model):
    
    cuenta = models.ForeignKey(Cuenta, on_delete = models.RESTRICT)
    fecha = models.DateField()
    cantidad = models.DecimalField(decimal_places = 2, max_digits = 10)

    TYPE = (
        ('n', 'Pago de Nómina'),
        ('p', 'Pago a proveedores'),
        ('r', 'Reembolso de gastos'),
        ('t', 'Traslado de efectivo entre entidades bancarias')
    )

    tipo = models.CharField(
        max_length=1,
        choices=TYPE,
        default='pn'
    )

    cuenta_origen = models.CharField(max_length = 36)

    def __str__(self):
      return f'transacción ${self.pk}'
  
    def get_absolute_url(self):
        return reverse('detalle-transaccion', args=[str(self.pk)])

class Financiamiento(models.Model):
    
    cuenta = models.ManyToManyField(Cuenta)

    FINANCING_TYPES = (
        ('p', 'Préstamo'),
        ('c', 'Crédito'),
    )

    tipo_financiamiento = models.CharField(
        max_length=1,
        choices= FINANCING_TYPES,
        default='c'
    )

    cantidad_prestamo = models.DecimalField(decimal_places = 2, max_digits = 10, null=True, blank=True )
    plazo= models.IntegerField(null=True, blank = True)
    tasa_interes = models.DecimalField(decimal_places = 2, max_digits = 10, null=True, blank = True)

    def __str__(self):
      return f'Financiamiento ${self.cuenta}'
  
    def get_absolute_url(self):
        return reverse('detalle-financiamiento', args=[str(self.pk)])

banco/views.py
from django import forms
from django.views import View
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from .models import Cliente, Cuenta, Transacciones


# Create your views here.

class DateInput(forms.DateInput):
    input_type = 'date'

class ClientForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = [
           'nombre',
           'apellido_paterno',
           'apellido_materno',
           'fecha_registro',
           'email'
        ]
        widgets = {
            'fecha_registro': DateInput()
        }
    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      for field in self.fields.values():
          field.widget.attrs['class'] = 'form-control'

def clients_list(request, template_name='clients_list.html'):
  clients = Cliente.objects.all()
  data = {}
  data['clients'] = clients
  return render(request, template_name, data)

def clients_create(request, template_name='clients_form.html'):
  form = ClientForm(request.POST or None)
  if form.is_valid():
      form.save()
      return redirect('clients_list')
  return render(request, template_name, {'form':form, 'title': 'Crear cliente'})

def clients_update(request, pk, template_name='clients_form.html'):
  client= get_object_or_404(Cliente, pk=pk)
  form = ClientForm(request.POST or None, instance=client)
  if form.is_valid():
      form.save()
      return redirect('clients_list')
  return render(request, template_name, {'form':form, 'title': 'Actualizar cliente'})

def clients_delete(request, pk, template_name='confirm_delete.html'):
  client= get_object_or_404(Cliente, pk=pk)    
  if request.method=='POST':
      client.delete()
      return redirect('clients_list')
  return render(request, template_name, {'object':client, 'title': 'cuenta'})

def accounts_list(request, client, template_name='accounts_list.html'):
  try: 
    accounts = get_list_or_404(Cuenta, cliente=client)
  except Exception as error:
    print("Error al obtener cuentas", error)
    accounts = []
  try:
     client_obj = get_object_or_404(Cliente, id=client)
  except Exception as error:
     print("Error al obtener cliente", error)
     client_obj = {"nombre": "unknown", "apellido_paterno": "user"}
  data = {}
  data['accounts'] = accounts
  data['client_id'] = client
  print("Este es el cliente obj", client_obj)
  data['client_name'] = f'{client_obj.nombre} {client_obj.apellido_paterno}'
  return render(request, template_name, data)


class AccountForm(forms.ModelForm):
    class Meta:
        model = Cuenta
        fields = ['asesor', 'cliente', 'feha_creacion', 'status', 'tipo_cuenta', 'balance' ]
        widgets = {
            'feha_creacion': DateInput()
        }

    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      for field in self.fields.values():
          field.widget.attrs['class'] = 'form-control'
        


def accounts_create(request, client_id, template_name='clients_form.html'):
  form = AccountForm(request.POST or None, initial={'cliente' : client_id})
  if form.is_valid():
      form.save()
      return redirect('clients_list')
  return render(request, template_name, {'form':form, 'title': "Crear cuenta"})

def account_update(request, pk, template_name='clients_form.html'):
  account= get_object_or_404(Cuenta, pk=pk)
  form = AccountForm(request.POST or None, instance=account)
  if form.is_valid():
      form.save()
      return redirect('clients_list')
  return render(request, template_name, {'form':form, 'title': 'Actualizar cuenta'})

def account_delete(request, pk, template_name='confirm_delete.html'):
  account= get_object_or_404(Cuenta, pk=pk)    
  if request.method=='POST':
      account.delete()
      return redirect('clients_list')
  return render(request, template_name, {'object':account, 'title': 'cuenta'})
  
  
class TransactionsView(View):
  def get(self, request, *args, **kwargs):
    transaction_id = kwargs['transaction']
    try:
      transactions = get_list_or_404(Transacciones, cuenta=transaction_id)
    except Exception as error:
      print("hubo un error", error)
      transactions = []
    return render(request, "transactions_list.html", {"transactions": transactions})

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transacciones
        fields = '__all__'
        widgets = {
            'fecha': DateInput()
        }
    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      for field in self.fields.values():
          field.widget.attrs['class'] = 'form-control'

def transaction_create(request, account, template_name='clients_form.html'):
  form = TransactionForm(request.POST or None, initial={'cuenta' : account})
  cliente_obj = Cuenta.objects.get(id=account)
  print("Este es balance", cliente_obj.balance)
  if form.is_valid():
      print("Este es form", form["cantidad"].value())
      cliente_obj.balance += int(form['cantidad'].value())
      form.save()
      cliente_obj.save()
      return redirect('clients_list')
  return render(request, template_name, {'form':form, 'title': "Nueva Transacción"})

banco/templates/accounts_list.html
{% extends "base.html" %} {% block content %}
<div style="margin: 2%">
<h2>Cuentas Bancarias de {{client_name}}</h2>
{% if accounts|length == 0 %}
<h3>Sin cuentas asociadas</h3>
{% endif %} 

<div style="display: flex; justify-content: flex-end">
  <a
    class="btn btn-primary rounded-pill"
    href="{% url 'account_create' client_id %}"
  >
    <div
      style="
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 5px;
      "
    >
      <i class="fa fa-plus-circle" aria-hidden="true"></i>
      <span>Agregar cuenta</span>
    </div></a
  >
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">No.cuenta</th>
      <th scope="col">Asesor</th>
      <th scope="col">Fecha Creación</th>
      <th scope="col">Tipo cuenta</th>
      <th scope="col">Estado</th>
      <th scope="col">Balance</th>
      <th scope="col">Acciones</th>
      <th scope="col">Transacciones</th>
    </tr>
  </thead>
  <tbody>
    {% for account in accounts %}
    <tr>
      <th scope="row">{{account.id}}</th>
      <td>{{account.asesor.all|join:", "}}</td>
      <td>{{account.feha_creacion}}</td>
      <td>{{account.get_tipo_cuenta_display}}</td>
      <td>{{account.get_status_display}}</td>
      <td>${{account.balance}}</td>
      <td>
        <div>
          <a class="btn btn-primary" href="{% url 'account_update' account.id %}">
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
          </a>
          <a
            type="button"
            class="btn btn-danger"
            href="{% url 'account_delete' account.id %}"
          >
            <i class="fa fa-trash-o" aria-hidden="true"></i>
          </a>
        </div>
      </td>
      <td>
        <a
            type="button"
            class="btn btn-primary"
            href="{% url 'transaction_create' account.id %}"
          >
            Crear
          </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<a class="btn btn-primary" href="/">Regresar</a>
</div>
{% endblock %}

banco/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/styles.css' %}"
    />
    <title>Entidad Bancaria</title>
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #145DA0;">
      <div class="container-fluid"">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">Clientes</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <div id="content">{% block content %} {% endblock %}</div>
  </body>
</html>

banco/templates/clients_form.html
{% extends "base.html" %} {% block content %}
<div style="margin: 3% 0">
  <form method="post">
    <div style="margin: 0 10%">
      <div class="forms-box">
        <div
          style="display: flex; width: 60%; flex-direction: column; gap: 15px"
        >
          <h2 style="text-align: center">{{title}}</h2>
          <hr class="dropdown-divider">
          {% csrf_token %} {% for field in form %}
          <div>
            <label for="{{field.name}}" class="form-label"
              >{{field.label}}</label
            >
            {{field}}
          </div>
          {% endfor %}
          <hr class="dropdown-divider">
        </div>
        
        <div class="d-grid gap-2 col-4 mx-auto">
          <input
            class="btn btn-success"
            style="margin-top: 10px"
            type="submit"
            value={{title}}
          />
          <a class="btn btn-info" style="margin-top: 10px" href="/">
            Regresar
          </a>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

banco/templates/clients_list.html
{% extends "base.html" %} {% block content %}
<div style="margin: 2%">
  <h2>Lista de clientes</h2>
  {% if clients|length == 0 %}
  <h3>Sin usuarios registrados</h3>
  {% endif %}

  <div style="display: flex; justify-content: flex-end">
    <a class="btn btn-primary rounded-pill" href="/clients/create">
      <div
        style="
          display: flex;
          justify-content: center;
          align-items: center;
          gap: 5px;
        "
      >
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
        <span> Nuevo usuario</span>
      </div></a
    >
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">No. Cliente</th>
        <th scope="col">Nombre</th>
        <th scope="col">Fecha Registro</th>
        <th scope="col">Correo Electrónico</th>
        <th scope="col">Cuentas</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for client in clients %}
      <tr>
        <th scope="row">{{client.id}}</th>
        <td>{{client.nombre}} {{client.apellido_paterno}}</td>
        <td>{{client.fecha_registro}}</td>
        <td>{{client.email}}</td>
        <td>
          <a class="btn btn-primary" href="{% url 'account_list' client.id %}">
            Ver
          </a>
        </td>
        <td>
          <div>
            <a class="btn btn-primary" href="{% url 'client_edit' client.id %}">
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            </a>
            <a
              type="button"
              class="btn btn-danger"
              href="{% url 'client_delete' client.id %}"
            >
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            </a>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

banco/templates/confirm_delete.html
{% extends "base.html" %} {% block content %}
<div style="margin: 3% 10%">
  <div class="forms-box">
    <div style="display: flex; width: 60%; flex-direction: column; gap: 15px">
      <h2>Eliminar {{title}}</h2>
      <form method="post">
        {% csrf_token %}
        <span>¿Está seguro de querer eliminar "{{ object }}" ?</span>
        <br />
        <div class="d-grid gap-2 col-4 mx-auto" style="margin-top: 5%;">
          <input class="btn btn-danger" type="submit" value="Eliminar" />
          <a class="btn btn-info" style="margin-top: 10px" href="/"> Cancelar </a>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

banco/templates/transactions_list.html
<!DOCTYPE html>
<html>
  <head>
    <title>Entidad bancaria</title>
  </head>
  <body>
    <h1>Lista de transacciones</h1>
    <ul>
      {% for transaction in transactions %}
      <li>{{ transaction.tipo }} - {{ transaction.cantidad }}</li>
      {% endfor %}
    </ul>
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
  </body>
</html>